### ISSUE TITLE
Question of the attention layer

### ISSUE THREAD

**Issue by xiaoleihuang** [cbaziotis/keras-utilities#1]
Hi, I implemented similar attention layer described in [Neural Machine Translation by Jointly Learning to Align and Translate](https://arxiv.org/abs/1409.0473), but I did not figure out the following line:
`
a = K.expand_dims(a)
`
Why should we expand the dimension here?

**Comment by cbaziotis** [comment]
I assume you are referring to [this line](https://github.com/cbaziotis/keras-utilities/blob/master/kutilities/layers.py#L132) in the `Attention` layer and/or [this line](https://github.com/cbaziotis/keras-utilities/blob/master/kutilities/layers.py#L227) in the `AttentionWithContext` layer. If not please tell me to which part you are referring to.

So let's say that we have sentences with `max_length` = 50 words and word embeddings with size 300. Then each sentence `x` is a (50,300) matrix and `a` is a vector (1D tensor) that holds the attention weights for each word (row of `x`). Here is the part that confuses you: 
```python
# shape of a is (50,) and shape of x is (50,300)

a /= K.cast(K.sum(a, axis=1, keepdims=True) + K.epsilon(), K.floatx())   # a's shape is (50,)

a = K.expand_dims(a)  # a's shape is (50, 1, )
weighted_input = x * a 
return K.sum(weighted_input, axis=1)
```
We turn `a` to a 1D vector so we can make the multiplication.

Here is a example using numpy:
```python
import numpy

x = numpy.array([
    [1, 2, 3, 5],
    [6, 7, 8, 9],
    [10, 11, 12, 13]
])
a = numpy.array([
    [0.2, 0.6, 0.2]
])
print(x.shape) # (3, 4)
print(a.shape) # (3,)
```
Now if we try to do this:
```python
print(x * a)
```
You will get an error: `ValueError: operands could not be broadcast together with shapes (3,4) (3,) `.
Instead, you need to expand the dimensions of `a`:
```python
print(x * numpy.expand_dims(a, axis=-1))  
```
Output:
```
[[ 0.2  0.4  0.6  1. ]
 [ 3.6  4.2  4.8  5.4]
 [ 2.   2.2  2.4  2.6]]
```

**Comment by xiaoleihuang** [comment]
Got it. Thanks!
