### ISSUE TITLE
ImportError: cannot import name 'initializations'

### ISSUE THREAD

**Issue by wooandoo** [cbaziotis/keras-utilities#2]
in keras-utilities/kutilities/layers.py

```python
from keras import initializations
```

"initializations" was now renamed "initializers" in Keras

it was changed in the Gist:
- https://gist.github.com/cbaziotis/6428df359af27d58078ca5ed9792bd6d
- https://gist.github.com/cbaziotis/7ef97ccf71cbc14366835198c09809d2

but not in this project :-(

**Comment by dhruvdcoder** [comment]
Facing the same issue

**Comment by cbaziotis** [comment]
I updated the project in order to work with Keras 2.X. Update and try again, it should be fine now.
```
pip install --no-cache-dir --upgrade keras-utilities
```
